### ISSUE TITLE
feature: Allow changing the validator set

### ISSUE THREAD

**Issue by sanjayprabhu** [farcasterxyz/snapchain#272]
Currently, we use a hardcoded validator set from config, and it's the same across time: https://github.com/farcasterxyz/snapchain/blob/04dc6e6decb3ac61e09ab1ad758104d7799a5723/src/consensus/validator.rs#L56-L58

This doesn't work when we need to change the validator set after some time (it will cause old blocks to be considered invalid if we just update the config etc).

So we need configuration something like:
```yaml

validator_set:
  - Initial
      shard: [0, 1, 2] # shard ids
      effective_at: 0 # block height
      validators: ['public key 1', ...]

 -  replace pk1
      shard: [0, 1, 2] 
      effective_at: 1000 // block height
      validators: ['public key 2', ...]
```

And whenever we query the validator set, we should return the right one based on the height requested (i.e. pk1 for blocks 0-1000 and pk2 got blocks > 1000).

This config file should be checked in and named based on the network (testnet/mainnet etc). The location of the file should be able to be overridden via config.
